dist: focal
sudo: required
language: c

os:
  - linux

script:
- sudo /bin/bash -c "
  echo Hello World
  && mkdir -p $HOME
  && cd $HOME
  && apt-get update
  && apt-get -qq -y dist-upgrade
  && DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
  && apt-get -qq -y install git make ocaml-findlib
  && git clone https://github.com/steve-cs/gnat-builder.git
  && cd gnat-builder
  && make prefix=/usr/local release-install
  && make spark2014
  "
