dist: focal
language: minimal

os:
  - linux

services:
  - docker

script:
- docker pull ubuntu:focal
- docker run ubuntu:focal /bin/bash -c "
  echo Hello World
  && mkdir -p $HOME
  && cd $HOME
  && apt-get update
  && DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
  && apt-get -qq -y install git make
  && git clone https://github.com/steve-cs/gnat-builder.git
  && cd gnat-builder
  && make prefix=/usr/local release-install
  && which gcc
  && gcc -v
  "
