dist: trusty
sudo: required
language: c

os:
  - linux

services:
  - docker

script:
- docker pull ubuntu:bionic
- docker run ubuntu:bionic /bin/bash -c "
  echo Hello World
  && export PATH=/usr/local/gnat/bin:$PATH
  && mkdir -p $HOME
  && cd $HOME
  && apt-get -qq update
  && apt-get -qq -y install ubuntu-standard git make
  && git clone https://github.com/steve-cs/gnat-builder.git
  && cd gnat-builder
  && make prerequisites-install
  && make release-download
  && make release-install
  "
